### ISSUE TITLE
Android 14 | GrapheneOs | Updates still showing in Play Store

### ISSUE THREAD

**Issue by ArminasAer** [j-hc/zygisk-detach#10]
I am on the latest GrapheneOs 10/13 Android 14 build
Pixel 6a Bluejay
Running the GrapheneOs play store sandbox
Playstore: 37.9.18-29
Magisk: 26.3
Zygisk-detach: 1.8

- cleared playstore storage and cache, force stop
- rebooted phone

Sidenote: thank you for all that you do!

![Screenshot_20231015-100435](https://github.com/j-hc/zygisk-detach/assets/22304079/97252e22-722f-4d4c-97da-8096caf7cebd)
![Screenshot_20231015-100411](https://github.com/j-hc/zygisk-detach/assets/22304079/0becc9c6-33f9-4431-a170-42b286036f52)
![Screenshot_20231015-100450](https://github.com/j-hc/zygisk-detach/assets/22304079/235d26fb-7723-4e60-86f7-15847d6a69ae)
![Screenshot_20231015-100441](https://github.com/j-hc/zygisk-detach/assets/22304079/b46768bf-ea89-4ff7-9444-5efaaf62e0d3)

**Comment by ArminasAer** [comment]
Running
su -c logcat -s "zygisk-detach" > /sdcard/log.txt

Just returns an empty .txt file, left the logcat open and redetached YouTube and YouTube music and the log file remains empty. So not sure what I am doing wrong there.

**Comment by j-hc** [comment]
does this work:
[zygisk-detach-v1.8t.zip](https://github.com/j-hc/zygisk-detach/files/12936067/zygisk-detach-v1.8t.zip)

**Comment by ArminasAer** [comment]
Removed 1.8
Restarted
Installed 1.8t
Restarted
Terminal ''su -c detach"
Detached youtube and youtube music
Cleared playstore storage/cache with force stop
Youtube and Youtube music are still showing in the playstore

Attached a link to the detach.bin file
https://drive.google.com/file/d/13VWPErX_ejJY--hkOebX7bcnPkwNt4hb/view?usp=drive_link

**Comment by j-hc** [comment]
This should produce logs. If it doesnt then zygisk isnt injected into play store for some reason.
[zygisk-detach-v1.6t.zip](https://github.com/j-hc/zygisk-detach/files/12936643/zygisk-detach-v1.6t.zip)

**Comment by ArminasAer** [comment]
> This should produce logs. If it doesnt then zygisk isnt injected into play store for some reason. [zygisk-detach-v1.6t.zip](https://github.com/j-hc/zygisk-detach/files/12936643/zygisk-detach-v1.6t.zip)

Here is the bin from 1.6t
https://drive.google.com/file/d/1_iRj7KQ1suIVnH3umLWb9i8RDGCKEFK4/view?usp=drive_link

**Comment by j-hc** [comment]
i need to see the logs taken with: "`su -c logcat -d | grep zygisk-detach > /sdcard/log.txt`" not the detach.bin file

and no idk if anyone on a14 is using zygisk-detach

**Comment by ArminasAer** [comment]
[log.txt](https://github.com/j-hc/zygisk-detach/files/12937194/log.txt)

**Comment by ArminasAer** [comment]
[log.txt](https://github.com/j-hc/zygisk-detach/files/12937389/log.txt)

**Comment by j-hc** [comment]
whats the output of this in termux: `su -c ls -l /data/adb/modules/zygisk-detach/detach.bin`

**Comment by ArminasAer** [comment]
> whats the output of this in termux: `su -c ls -l /data/adb/modules/zygisk-detach/detach.bin`

![Screenshot_20231017-103937](https://github.com/j-hc/zygisk-detach/assets/22304079/048829ae-b44e-4bbf-bc09-945d63c100be)

**Comment by ArminasAer** [comment]
@j-hc 
You can close this out, I flashed vanilla Android 14 on my 6a and this is now working with the latest 1.8 version. II am able to detach applications from the playstore correctly.

This issue is definitly tied to how grapehenos handles the playstore in sandbox mode. I would assum this module doesn't work on grapheneos android 13 as well. 

But yes, vanilla Google Android 14 is working with 1.8

Thank you for the support though!

**Comment by ArminasAer** [comment]
Wait... now both apps are back in the app store. So it was working for a couple minutes, but they are back now.

**Comment by j-hc** [comment]
tbh the issue wasnt about gmscompat. zygisk-detach wasnt able to read detach.bin. could be related to selinux idk

**Comment by ArminasAer** [comment]
Oh okay, well seems to be okay now on stock Android 14

Thank you again!
