### ISSUE TITLE
cant detached many apps

### ISSUE THREAD

**Issue by ickyx** [j-hc/zygisk-detach#12]
i just can detach 11 apps 
more that get error

[log.txt](https://github.com/j-hc/zygisk-detach/files/13255794/log.txt)

**Comment by j-hc** [comment]
yes thats the limit. detach.bin cant be larger than 512 bytes. i thought that would be enough for everybody. why are you trying to detach that many apps

**Comment by ickyx** [comment]
it's good if no limit
