### ISSUE TITLE
DETACH MODULE ISN'T WORKING ON ANDROID 14

### ISSUE THREAD

**Issue by thefaizanbashir** [j-hc/zygisk-detach#13]
![Screenshot_20231208-134913](https://github.com/j-hc/zygisk-detach/assets/79439907/a5e23644-0eee-4f36-8a2a-a22cd72d2302)
![Screenshot_20231208-135104](https://github.com/j-hc/zygisk-detach/assets/79439907/b777f830-df38-489f-81a1-c4274ee9e451)

**Comment by j-hc** [comment]
> Screenshot of Play Store page of the app you are trying to detach:
Screenshot of the helper CLI showing detached apps (from Option 2):
Logs taken with su -c logcat -s "zygisk-detach" > /sdcard/log.txt:
Not providing this information will get your issue closed
