### ISSUE TITLE
Unable to install some apps from the Play Store

### ISSUE THREAD

**Issue by SuchBlue** [j-hc/zygisk-detach#14]
**Screenshot of Play Store page of the app I am trying to detach:**
![Screenshot_20231217-140150_Google Play Store.png](https://github.com/j-hc/zygisk-detach/assets/58862188/bea5b4e0-ed6b-4c0a-a586-9d7ab621666e)

**Screenshot of the Play Store page of one of the apps I am unable to install:**
![Screenshot_20231217-135852_Google Play Store.png](https://github.com/j-hc/zygisk-detach/assets/58862188/a09110a8-1dc6-44cd-9ef1-9ce9acc838dc)

Many apps don't work.. this is just an example. 

**Screenshot of the helper CLI showing detached apps (from Option 2):**
![Screenshot_20231217-140041_Termux.png](https://github.com/j-hc/zygisk-detach/assets/58862188/f850f161-8edb-4162-b729-daadfdea2c86)

**Logs taken with `su -c logcat -s "zygisk-detach" > /sdcard/log.txt`:**
```
--------- beginning of main
12-17 13:55:11.539  1746  1747 D zygisk-detach: ERROR: companion open
12-17 13:55:11.539 11560 11560 D zygisk-detach: ERROR: detach.bin <= 0
12-17 13:55:12.199  1746  1747 D zygisk-detach: ERROR: companion open
12-17 13:55:12.200 11652 11652 D zygisk-detach: ERROR: detach.bin <= 0
```

**Comment by j-hc** [comment]
magisk or kernelsu? or a fork of magisk?

**Comment by SuchBlue** [comment]
Regular Magisk 26.4

![Screenshot_20231217-144310_RSettings.png](https://github.com/j-hc/zygisk-detach/assets/58862188/cd7c5470-822d-4cb6-8049-9ec14ebf3fa8)

![Screenshot_20231217-144314_RSettings.png](https://github.com/j-hc/zygisk-detach/assets/58862188/5fbec316-2cda-4364-a2a9-55404da1298e)

**Comment by j-hc** [comment]
can you try with other modules disabled?

**Comment by SuchBlue** [comment]
Still happens

![Screenshot_20231217-165750_RSettings.png](https://github.com/j-hc/zygisk-detach/assets/58862188/b49c0120-bb16-4e45-b498-96e51e5d701a)

![Screenshot_20231217-165742_Google Play Store.png](https://github.com/j-hc/zygisk-detach/assets/58862188/483c5185-a94c-49cf-9410-757bda8c0bfc)

**Comment by j-hc** [comment]
are logs different after disabling others?

**Comment by SuchBlue** [comment]
I don't even get any output executing that command, and it writes nothing to /sdcard/log.txt, so I guess there aren't even any errors :(

**Comment by SuchBlue** [comment]
Although it rarely (not never) does manage to install the app after trying to install a few other different apps, but it's quite tedious and definitely not working as it should be.

**Comment by j-hc** [comment]
i might have fix for running with other modules like shamiko. other than that, idk why it still fails. did you try clearing the data of play store?

**Comment by SuchBlue** [comment]
clearing the storage of the play store seemed to fix it! i don't know why i didn't think of that, but maybe anyone who is experiencing the same issue and wasn't able to solve it sees this issue 😅
