### ISSUE TITLE
Increase detach.bin size and...

### ISSUE THREAD

**Issue by acwcanada** [j-hc/zygisk-detach#19]
**Screenshot of Play Store page of the app you are trying to detach:**

**Screenshot of the helper CLI showing detached apps (from Option 2):**

**Logs taken with `su -c logcat -s "zygisk-detach" > /sdcard/log.txt`:**

Not providing this information will get your issue closed

Not a bug report but just two questions hope to have be answered:

1. Right now the detach.bin file is limited to 1024b, is it possible to allow a bigger size thus enable to get more apps to be detached?
2.  Overtime, forgot what apps has been detached, is there a way to generate a detach.txt ?

Thanks

**Comment by j-hc** [comment]
1. how many apps you need to detach?
2. use option 2 in cli to see

**Comment by acwcanada** [comment]
> 1. how many apps you need to detach?
> 2. use option 2 in cli to see

Besides the revanced apps, I have perhaps around 20 more apps which I don't like to be updated as I like their older features, I found that I am just I little bit short with that 1024b. Anyway, sorry for my asking. Oh! I forgot that I can use the option 2, thanks that would resolve my needing.

**Comment by j-hc** [comment]
did you actually hit the limit. 1024b should be enougj

**Comment by acwcanada** [comment]
> did you actually hit the limit. 1024b should be enougj

I couldn't remember exactly how many I have wanted to detach, just remembered when I was at my last one, it gave me the error that I have over the limit which is 1022b and the last one couldn't be detached. Like you said, not many people wanted to detach so many apps like me, so just forget it and no bother to waste of your time. Thanks
