### ISSUE TITLE
Zygisk detach module doesn't work

### ISSUE THREAD

**Issue by WibuCTer** [j-hc/zygisk-detach#2]
![IMG_20230903_001509_944](https://github.com/j-hc/zygisk-detach/assets/126878979/ab7b5dbc-1316-452f-b389-46b114197d55)
It doesn't work (zygisk enabled, magisk 25.2)

**Comment by j-hc** [comment]
update your magisk

**Comment by kazimmt** [comment]
> update your magisk

For some people, latest magisk is unstable

**Comment by WibuCTer** [comment]
> > update your magisk
> 
> For some people, latest magisk is unstable

Yep

**Comment by j-hc** [comment]
report that to magisk then, zygisk api v4 is only supported at magisk version >= 26.1

**Comment by kazimmt** [comment]
Make sense
Than you
