### ISSUE TITLE
Apps still appear in playstore even after running detach

### ISSUE THREAD

**Issue by ashoktvm** [j-hc/zygisk-detach#20]
**
[image](https://github.com/j-hc/zygisk-detach/assets/45116583/f9d235ee-bd83-4238-9526-3effc9090fdd)
**

**
[image](https://github.com/j-hc/zygisk-detach/assets/45116583/359b53cb-f107-443b-92b5-c13116825a4d)**
You can see the program at the end

**Logs taken with `su -c logcat -s "zygisk-detach" > /sdcard/log.txt`:** : After running this command log,txt is created but there is nothing in the file and in termux it shows nothing
[image](https://github.com/j-hc/zygisk-detach/assets/45116583/63cf9061-fb2c-494d-ac04-dff5817fbcf7)

I am using kernelsu by the way for root permissions

**Comment by j-hc** [comment]
> I am using kernelsu by the way for root permissions

did you flash zygisknext as per the readme?

**Comment by ashoktvm** [comment]
> > I am using kernelsu by the way for root permissions
> 
> did you flash zygisknext as per the readme?

Yes it's already installed.

**Comment by j-hc** [comment]
disable zygisksu and zygisk-detach. reboot. enable both and reboot again.

**Comment by ifsvivek** [comment]
Yeah, facing same issue

**Comment by j-hc** [comment]
Send logs or dont comment.

**Comment by ifsvivek** [comment]
> comments without logs are unnecessary.

Yeah, i tried the to take log using the code
`su -c logcat -s "zygisk-detach" > /sdcard/log.txt`
But it just created a filenames log.txt with 0byte size.

I have also tried multiple times reinstalling both of the modules (zygisk and detach) but still no luck.

**Comment by j-hc** [comment]
> > comments without logs are unnecessary.
> 
> Yeah, i tried the to take log using the code `su -c logcat -s "zygisk-detach" > /sdcard/log.txt` But it just created a filenames log.txt with 0byte size.
> 
> I have also tried multiple times reinstalling both of the modules (zygisk and detach) but still no luck.

Did you read the readme? Did you follow all the steps?

**Comment by ifsvivek** [comment]
> > > comments without logs are unnecessary.
> > 
> > 
> > Yeah, i tried the to take log using the code `su -c logcat -s "zygisk-detach" > /sdcard/log.txt` But it just created a filenames log.txt with 0byte size.
> > I have also tried multiple times reinstalling both of the modules (zygisk and detach) but still no luck.
> 
> Did you read the readme? Did you follow all the steps?

Yes sir, it happened yesterday for me. Before that everything was normal

**Comment by j-hc** [comment]
> > > > comments without logs are unnecessary.
> > > 
> > > 
> > > Yeah, i tried the to take log using the code `su -c logcat -s "zygisk-detach" > /sdcard/log.txt` But it just created a filenames log.txt with 0byte size.
> > > I have also tried multiple times reinstalling both of the modules (zygisk and detach) but still no luck.
> > 
> > Did you read the readme? Did you follow all the steps?
> 
> Yes sir, it happened yesterday for me. Before that everything was normal

I need every info stated here:
https://github.com/j-hc/zygisk-detach/blob/master/.github%2FISSUE_TEMPLATE%2Fbug_report.md

**Comment by ifsvivek** [comment]
![Screenshot_20231230-003503_Google Play Store](https://github.com/j-hc/zygisk-detach/assets/80456739/eb68f299-f13e-41f8-968e-6175cc4f486a)
![Screenshot_20231230-003528_Termux](https://github.com/j-hc/zygisk-detach/assets/80456739/875c3e17-5752-4a09-9ea7-d8662072aa48)
![Screenshot_20231230-003534_Termux](https://github.com/j-hc/zygisk-detach/assets/80456739/22f34bf4-7dad-4fcc-ab26-508aaf9e6853)
![Screenshot_20231230-003547_KernelSU](https://github.com/j-hc/zygisk-detach/assets/80456739/a367adca-c939-444a-94d0-d02c842421eb)

Running: Elixer Os with N0KERNEL A13
Phone : Mi 11x 


Logs:
![Screenshot_20231230-003858_Termux](https://github.com/j-hc/zygisk-detach/assets/80456739/cdb63019-affb-49fa-a938-42e98cbd0e04)
![Screenshot_20231230-003903_ZArchiver](https://github.com/j-hc/zygisk-detach/assets/80456739/23cedee4-dfdc-4184-9624-b662e44696ec)
[log.txt](https://github.com/j-hc/zygisk-detach/files/13795616/log.txt)


Even after running the detach again the log file doesn't update
![Screenshot_20231230-004024_Termux](https://github.com/j-hc/zygisk-detach/assets/80456739/37ef9f20-ec92-49b7-984d-19a62f3e5186)
![Screenshot_20231230-004036_ZArchiver](https://github.com/j-hc/zygisk-detach/assets/80456739/1616a6bb-d209-4b84-a043-b3afd1f320d0)

**Comment by j-hc** [comment]
@ifsvivek 
get logs with this build: 
[zygisk-detach-v1.9.1t.zip](https://github.com/j-hc/zygisk-detach/files/13795688/zygisk-detach-v1.9.1t.zip)

and please edit your comment to not include full size images.

**Comment by ifsvivek** [comment]
> @ifsvivek get logs with this build: [zygisk-detach-v1.9.1t.zip](https://github.com/j-hc/zygisk-detach/files/13795688/zygisk-detach-v1.9.1t.zip)


[log.txt](https://github.com/j-hc/zygisk-detach/files/13796738/log.txt)
![Screenshot_20231230-064425_Termux](https://github.com/j-hc/zygisk-detach/assets/80456739/667ef76d-4059-471a-aa21-8f52e701cae8)

Also it works now, YouTube is detached from playstore

**Comment by j-hc** [comment]
I didnt change anything so it was always working. It was a zygisknext bug most probably. Im closing the issue.
