### ISSUE TITLE
Messeger not detach

### ISSUE THREAD

**Issue by Apurbokumarmajumder** [j-hc/zygisk-detach#23]
![WhatsApp Image 2024-01-04 at 20 36 44_1761d01c](https://github.com/j-hc/zygisk-detach/assets/134644190/b0192a91-841d-4f0a-96d5-144a2883d5b4)

**Comment by j-hc** [comment]
you need the package name

**Comment by Apurbokumarmajumder** [comment]
how to find it?

**Comment by j-hc** [comment]
go to the app's play store website. package name is the last part of the url.
