### ISSUE TITLE
detach: inaccessible or not found on latest ZygiskNext build

### ISSUE THREAD

**Issue by collisee** [j-hc/zygisk-detach#24]
As the title said, running "detach" using latest zygisknext (v4-0.9.0) doesn't work at all
Running on MIUI 14.0.7.0
The log is empty
Screenshot
![Screenshot_2024-01-05-01-56-53-343_jgmwjk r uqhesddp](https://github.com/j-hc/zygisk-detach/assets/136151261/40406f2d-62d0-4eb5-987b-0218441c6c06)
![Screenshot_2024-01-05-01-54-14-996_com termux-edit](https://github.com/j-hc/zygisk-detach/assets/136151261/2bec80e0-a4ff-4c9c-ba95-ea0a3a71285b)

**Comment by j-hc** [comment]
are you using a fork of magisk? only official magisk and kernelsu are supported.

**Comment by j-hc** [comment]
and what does this show in termux:
`su -c /data/adb/modules/zygisk-detach/system/bin/detach`

**Comment by collisee** [comment]
detach ran like normal with that command
![Screenshot_2024-01-05-06-02-46-576_com termux-edit](https://github.com/j-hc/zygisk-detach/assets/136151261/59f213c4-ebae-4891-a4d1-21083103eec6)

**Comment by j-hc** [comment]
its the magisks problem you are using then

**Comment by nyakze** [comment]
I have the same issue on KernelSU 11986 (v1.0.2 manager) with ZygiskNext 1.2.7

**Comment by nyakze** [comment]
Same KSU 12018 (1.0.3 manager). Can't reopen issue for some reason @j-hc

**Comment by j-hc** [comment]
`su -c /data/adb/modules/zygisk-detach/detach`

**Comment by nyakze** [comment]
> `su -c /data/adb/modules/zygisk-detach/detach`

Yes that works on the latest version. 
Downgrading to zygisk-detach 1.18.0 makes `su -c detach` work, which is much more convenient to use.
