### ISSUE TITLE
detach Module crash when selecting cmd option 1

### ISSUE THREAD

**Issue by machtoners** [j-hc/zygisk-detach#27]
**Are you sure you read the [readme](https://github.com/j-hc/zygisk-detach#usage)?**
Yes
**Android version and skin (MIUI etc... is MIUI still a thing? idk):**
AOSP 14
**Screenshot of Play Store page of the app you are trying to detach:**

**Screenshot of the helper CLI showing detached apps (from Option 2):**
Reddit for Android
**Logs taken with `su -c logcat -d -s "zygisk-detach" > /sdcard/log.txt`:**
Attached
![Screenshot_20240121-162556](https://github.com/j-hc/zygisk-detach/assets/94160902/53b468f2-1260-4dcf-9658-5fc381ea6791)
![Screenshot_20240121-162704](https://github.com/j-hc/zygisk-detach/assets/94160902/f2622327-9f1f-46f7-9aa7-6fffd5cebbe0)
[log.txt](https://github.com/j-hc/zygisk-detach/files/14000992/log.txt)

Not providing this information will get your issue closed

**Comment by j-hc** [comment]
should be fixed with v1.10.1
