### ISSUE TITLE
more than 10 entries possible ?

### ISSUE THREAD

**Issue by Metalomeus** [j-hc/zygisk-detach#28]
**Are you sure you read the [readme](https://github.com/j-hc/zygisk-detach#usage)?**

Yep 

**Android version and skin (MIUI etc... is MIUI still a thing? idk):**

Aosp14

**Screenshot of Play Store page of the app you are trying to detach:**

**Screenshot of the helper CLI showing detached apps (from Option 2):**

**Logs taken with `su -c logcat -d -s "zygisk-detach" > /sdcard/log.txt`:**

Not providing this information will get your issue closed

**Comment by j-hc** [comment]
yes?

**Comment by Metalomeus** [comment]
> yes?

Whatever the question mark means....you could consider it in a update maybe...

**Comment by j-hc** [comment]
the limit is not 10 apps. what make you think its not possible to detach more than 10 apps?

**Comment by Metalomeus** [comment]
> the limit is not 10 apps. what make you think its not possible to detach more than 10 apps?

Because if I detached the 11th app all apps previously detached reappear in play store.... that's why I ask if there's a limit....

**Comment by j-hc** [comment]
the limit is not 10. there is a limit but before you reach it, the cli stops you so you dont exceed it.
if you are still having problems open a proper issue with logs or it will be closed again.
