### ISSUE TITLE
[port request] Alternative for those of us with Zygisk incompatibe phones

### ISSUE THREAD

**Issue by LeeBinder** [j-hc/zygisk-detach#29]
**Are you sure you read the [readme](https://github.com/j-hc/zygisk-detach#usage)?** YES

**Android version and skin (MIUI etc... is MIUI still a thing? idk):** Samsung Galaxy A8 with stock Android 9 ROM + latest Magisk + latest LSPosed (my 2ndary mobile)

Hi @j-hc I couldn't supply the other information since it doesn't apply because (as 2ndary) I run one of these phone ROMs which has issues with LSPosed Zygisk, which is known to the LSPosed team so they suggest running Riru + LSPosed Riru (for such cases still fully maintained and kept as current as the Zygisk port), for which Zygisk needs to be disabled. Consequently I can't run zygisk-detach.

Therefore my general question if it's feasible to also create riru-detach?

Would be awesome to hear your feedback.

**Comment by j-hc** [comment]
riru is not one-to-one compatible with zygisk api v4 so unfortunately no i cant port zygisk-detach to riru.

**Comment by LeeBinder** [comment]
gotcha, thanks for the clarification. I'm using [Xposed Hide My Applist](https://github.com/Dr-TSNG/Hide-My-Applist) on that phone which works as supposed. I just always prefer a Magisk- over an Xposed module. Luckily it only requires System Framework to be enabled in its LSPosed settings, so the footprint should be minimal.
