### ISSUE TITLE
Zygisk detach is not working in kernelsu

### ISSUE THREAD

**Issue by ohmypxl** [j-hc/zygisk-detach#3]
I've tried the module with [Zygisk on KernelSU](https://github.com/Dr-TSNG/ZygiskOnKernelSU), at first everything seem fine until i found out that youtube actually update itself even though it's on the detach list.

Screenshots
![Screenshot_20230905-050354696](https://github.com/j-hc/zygisk-detach/assets/104730381/fab90fd8-de9c-4453-8e5a-166dcc4ce04d)
![Screenshot_20230905-050403962](https://github.com/j-hc/zygisk-detach/assets/104730381/4c1377ff-d740-4d89-a217-eb50842fa004)

The detach.bin (inside the zip file)
[detach.zip](https://github.com/j-hc/zygisk-detach/files/12516929/detach.zip)

**Comment by j-hc** [comment]
does youtube play store page show "uninstall" button

**Comment by ohmypxl** [comment]
> does youtube play store page show "uninstall" button

I haven't checked it, but i think there is a button that says "uninstall" after "open" button.

**Comment by j-hc** [comment]
then detach doesnt work. join telegram group for a test module to debug the issue
https://t.me/rv_magisk

**Comment by j-hc** [comment]
fixed in 1.6

**Comment by AsterITA** [comment]
Hi I encountered the same problem with youtube, here a screen from KSU modules:
![immagine](https://github.com/j-hc/zygisk-detach/assets/7688157/24628923-036d-4ca2-ade3-5e82ea96265b)

This is the file I installed with the detach.txt inside:
[zygisk-detach-v1.6.zip](https://github.com/j-hc/zygisk-detach/files/12717283/zygisk-detach-v1.6.zip)

**Comment by j-hc** [comment]
> > fixed in 1.6
> 
> Hi I encountered the same problem with youtube using the `detach.txt` file, here a screen from KSU modules: 
> 
> This is the file I installed with the detach.txt inside: [zygisk-detach-v1.6.zip](https://github.com/j-hc/zygisk-detach/files/12717283/zygisk-detach-v1.6.zip)
> 
> Instead if I configure the detach from CLI it works without any problem

latest commit fixes this and it will be available in next release v1.7
