### ISSUE TITLE
Bigger detach.bin

### ISSUE THREAD

**Issue by 9cento** [j-hc/zygisk-detach#30]
**Are you sure you read the [readme](https://github.com/j-hc/zygisk-detach#usage)?** Yes

**Android version and skin (MIUI etc... is MIUI still a thing? idk):** Android 14 (Google Pixel)

**Screenshot of Play Store page of the app you are trying to detach:**

**Screenshot of the helper CLI showing detached apps (from Option 2):**

**Logs taken with `su -c logcat -d -s "zygisk-detach" > /sdcard/log.txt`:**

Not providing this information will get your issue closed

Can we please have a bigger detach.bin?
Being unable to detach more than 11 apps is very limiting for such a useful and versatile module.
Thanks for your hard work, much appreciated!

**Comment by j-hc** [comment]
there is no limit in v1.11.0
