### ISSUE TITLE
Play Store crash with module OhMyFonts installed

### ISSUE THREAD

**Issue by jorgedasilva91** [j-hc/zygisk-detach#31]
--------- beginning of main
02-02 10:13:24.701 18088 18088 D zygisk-detach: Loaded!

**Comment by yuzamei2854** [comment]
> When I try to open PlayStore it crashes. Se desativar o módulo das fonts tufo volta a funcionar. consegue corrigir?

Por favor, fale em inglês, o português não deve ser a língua principal do programador.

Please speak in english, portuguese should not be the developer's main language.

**Comment by j-hc** [comment]
most likely a play store bug. cant reproduce, and you didnt provide any logs either.
