### ISSUE TITLE
Google phone still auto update even if disappear on play store

### ISSUE THREAD

**Issue by JasonKwokGJQ** [j-hc/zygisk-detach#34]
I downgraded the Google phone to 94.0 and followed all the steps to install zygisk-detach successfully, Google phone disappeared on the update list but after a while, it still automatically updated to version 108 which is not the lastest one. How can I fix that?

**Are you sure you read the [readme](https://github.com/j-hc/zygisk-detach#usage)?**
Yes
**Android version and skin (MIUI etc... is MIUI still a thing? idk):**
Pixel 7 Android 14 original

**Screenshot of Play Store page of the app you are trying to detach:**
![4122ccfd360e0f434d7cbcec0634fc2](https://github.com/j-hc/zygisk-detach/assets/36097529/09322700-e4e5-4440-8d1d-2096df2cf0d9)

**Screenshot of the helper CLI showing detached apps (from Option 2):**
![cd73e453cebfd62d6623874865d8ae3](https://github.com/j-hc/zygisk-detach/assets/36097529/11fc3c9a-c416-4f7c-b070-075adea5d336)

**Logs taken with `su -c logcat -d -s "zygisk-detach" > /sdcard/log.txt`:**
The log file is empty
Not providing this information will get your issue closed

**Comment by j-hc** [comment]
try v1.13.0
