### ISSUE TITLE
May cause Play Store crash.

### ISSUE THREAD

**Issue by moleoxa** [j-hc/zygisk-detach#39]
**Are you sure you read the [readme](https://github.com/j-hc/zygisk-detach#usage)?**
Yes

**Android version and skin (MIUI etc... is MIUI still a thing? idk):**
Environment: 
Device: Oneplus 12R
OS: Android 14 Coloros 14.0
Google Play Store: 40.5.30-31_0
App:  zygisk-detach 1.15.0

Maybe caused by the same reason of this issue.
>https://github.com/j-hc/zygisk-detach/issues/18

Test:
1. Flash zygisk-detach with a detach.txt(com.google.android.youtube)
2. Google Play Store (GPS) quickly quit while launching.
3. Uninstall and Clean GPS, still not work.
4. Remove zygisk-detach. GPS Work Fine.

**Comment by moleoxa** [comment]
Oh I am sorry not to see these already closed issue.

https://github.com/j-hc/zygisk-detach/issues/38
https://github.com/j-hc/zygisk-detach/issues/31
https://github.com/j-hc/zygisk-detach/issues/21
https://github.com/j-hc/zygisk-detach/issues/11
https://github.com/j-hc/zygisk-detach/issues/4

Fortunatlely, zygisk-detach work fine with GPS on my Poco F5 (Android 14 HyperOS 1.0.2.0)

**Comment by moleoxa** [comment]
Rollback to v1.13.0. Still not work.

**Comment by j-hc** [comment]
follow the issue template fully. you didnt provide logs
