### ISSUE TITLE
Question about deny list 

### ISSUE THREAD

**Issue by Turhvjbufv** [j-hc/zygisk-detach#41]
Can detach be used if play store and other play store service are on deny list?
Couldn't find anywhere else and wanted to make sure before using it

**Comment by j-hc** [comment]
if you add play store in denylist, no zygisk module will work for play store including zygisk-detach. thats why the module will remove it from denylist even if you add it.

for gms, its fine to add to denylist

**Comment by j-hc** [comment]
arent those module hooking in play store? if you add it to denylist, those modules wont work either. i dont use them so i dont know about the specifics
