### ISSUE TITLE
Failed to detach app

### ISSUE THREAD

**Issue by stan618** [j-hc/zygisk-detach#42]
**Are you sure you read the [readme](https://github.com/j-hc/zygisk-detach#usage)?**
Yes
**Android version and skin (MIUI etc... is MIUI still a thing? idk):**
Redmi Note 8 Pro, VoltageOs Android 14
**Screenshot of Play Store page of the app you are trying to detach:**
[photo_2024-05-22_12-31-28](https://github.com/j-hc/zygisk-detach/assets/93877247/e30db0a1-2620-40b3-bea9-01e6cdef629c)
[photo_2024-05-22_12-31-14](https://github.com/j-hc/zygisk-detach/assets/93877247/4b21c8f6-9d66-4e5d-bb1f-3298a6100441)
**Screenshot of the helper CLI showing detached apps (from Option 2):**
[photo_2024-05-22_12-29-48](https://github.com/j-hc/zygisk-detach/assets/93877247/e7708f71-c499-44b2-9f28-02dc96b13c0a)
**Logs taken with `su -c logcat -d -s "zygisk-detach" > /sdcard/log.txt`:**
[log.txt](https://github.com/j-hc/zygisk-detach/files/15399675/log.txt)
Empty log, but still uploaded for template
Not providing this information will get your issue closed

**Comment by j-hc** [comment]
if the logs are empty, then the module did not event start which is a bug of your setup.

magisk/kernelsu? what are the other modules?

**Comment by stan618** [comment]
> if the logs are empty, then the module did not event start which is a bug of your setup.
> 
> magisk/kernelsu? what are the other modules?

kernelsu. I have installed a few other modules which are shown below:

![photo_2024-05-22_15-37-55](https://github.com/j-hc/zygisk-detach/assets/93877247/cf97a3fc-ca5a-4503-8967-520b5a58b774)

![photo_2024-05-22_15-38-01](https://github.com/j-hc/zygisk-detach/assets/93877247/a9bed3b7-bb8d-4bbc-8dea-3a54dc82c6c6)

**Comment by stan618** [comment]
> if the logs are empty, then the module did not event start which is a bug of your setup.
> 
> magisk/kernelsu? what are the other modules?

Kernelsu. I have a few other modules installed which are shown below:

![photo_2024-05-22_15-37-55](https://github.com/j-hc/zygisk-detach/assets/93877247/1304768d-ad84-4324-ae5e-3d3f6d6ec12e)
![photo_2024-05-22_15-38-01](https://github.com/j-hc/zygisk-detach/assets/93877247/f292096a-3617-419e-a662-a7d7436aa3f8)

**Comment by j-hc** [comment]
there is no zygisk-detach with version v1.17.0

**Comment by stan618** [comment]
> there is no zygisk-detach with version v1.17.0

I have installed the latest version (v1.16.1) but unfortunately, it still wont get detached.

![Screenshot_20240522-155803](https://github.com/j-hc/zygisk-detach/assets/93877247/46a33cb5-4bb8-4d4e-95a0-165a7176108d)
![Screenshot_20240522-155820](https://github.com/j-hc/zygisk-detach/assets/93877247/eb0bea1a-ef00-4d49-8f97-da4f80e2d869)
![Screenshot_20240522-155846](https://github.com/j-hc/zygisk-detach/assets/93877247/02a50e68-6299-4232-a58c-6649915dd98d)
![Screenshot_20240522-155851](https://github.com/j-hc/zygisk-detach/assets/93877247/0d2103df-0abc-4315-bda5-b2fee1e84956)
![Screenshot_20240522-155857](https://github.com/j-hc/zygisk-detach/assets/93877247/3635cdec-c00c-417c-a257-a300563ed0aa)

**Comment by j-hc** [comment]
idk. try reinstalling zygisknext. like i said its a bug of your setup or the other modules you use. there is nothing i can fix here.

**Comment by stan618** [comment]
I tried uninstalling and re-installing Zygisknext but it still doesn't detach. Is the one im using the correct one? (v1.0.5)
