### ISSUE TITLE
Loses detached apps

### ISSUE THREAD

**Issue by jimger** [j-hc/zygisk-detach#43]
**Are you sure you read the [readme](https://github.com/j-hc/zygisk-detach#usage)?**
Yes

**Android version and skin (MIUI etc... is MIUI still a thing? idk):**
Oxygen OS. Android 14

**Screenshot of Play Store page of the app you are trying to detach:**
Doesn't matter 

**Screenshot of the helper CLI showing detached apps (from Option 2):**

**Logs taken with `su -c logcat -d -s "zygisk-detach" > /sdcard/log.txt`:**
Comes back empty 

Not providing this information will get your issue closed
  
It loses track which apps should be detached. No idea why

**Comment by j-hc** [comment]
> Screenshot of the helper CLI showing detached apps (from Option 2):

not provided

> Logs taken with su -c logcat -d -s "zygisk-detach" > /sdcard/log.txt:
Comes back empty

if the logs are empty then the issue is with your setup. zygisk-detach never run at all on your device.
