### ISSUE TITLE
Overflowing index out of range

### ISSUE THREAD

**Issue by Nek-12** [j-hc/zygisk-detach#49]
panicked at src/main.rs:417:41:
                               range end index 18446744073709551615 out of range for slice of length 0

This should not have happened.

**Android version and skin (MIUI etc... is MIUI still a thing? idk):**
A14 OxygenOS

**Screenshot of Play Store page of the app you are trying to detach:**
YouTube 

**Screenshot of the helper CLI showing detached apps (from Option 2):**
None 

**Logs taken with `su -c logcat -d -s "zygisk-detach" > /sdcard/log.txt`:**
Created an empty file 

Not providing this information will get your issue closed

**Comment by j-hc** [comment]
fixed b8a04ab
