### ISSUE TITLE
"Target does not exist in denylist"

### ISSUE THREAD

**Issue by Jrmewam** [j-hc/zygisk-detach#50]
**Are you sure you read the [readme](https://github.com/j-hc/zygisk-detach#usage)?**
yes

**Android version and skin (MIUI etc... is MIUI still a thing? idk):**
latest official Pixel 5 rom, and latest zygisk-detach 1.18.0

**Logs taken with `su -c logcat -d -s "zygisk-detach" > /sdcard/log.txt`:**
just says that zygisk-detach is loaded

Issue:
After detaching an app (both in Termux or with the zygisk-detach-app), restart zygisk-detach in Termux. There's a message "Target does not exist in denylist" before the "do not put play store in denylist" warning.
When checking at the detach.bin, I noticed theres a "!" added after the first package's name in the list.

Doesn't seem to have any effect but I thought you might want to know, otherwise sorry for bothering :)

**Comment by j-hc** [comment]
> When checking at the detach.bin, I noticed theres a "!" added after the first package's name in the list.

detach.bin uses a binary format, you cant just open it with a text editor

> There's a message "Target does not exist in denylist" before the "do not put play store in denylist" warning.

fixed b8a04ab
