### ISSUE TITLE
Magisk detected

### ISSUE THREAD

**Issue by cawhyred** [j-hc/zygisk-detach#52]
Hi, After flashing this module some banking app does not work because they detect magisk installation even though I am rooted with KernelSU.

I checked with Momo and can see magisk being detected. I don't know much about how this module works, but is their a possibility to use other methods which will not result in magisk being installed.

![Screenshot_20240930-200638_crDroid Home](https://github.com/user-attachments/assets/9abd4735-040d-411b-baed-6b9735fc1475)

**Comment by itsvngo** [comment]
As I experienced before, momo can even detect the status of phone's bootloader. If the bootloader is unlocked, momo won't work. Still, you want to use momo, your best bet is going back to stock rom with locked bootloader or use the app on another phone.

**Comment by j-hc** [comment]
zygisk-detach only hooks into play store, there is nothing else i can do. try denylist.

**Comment by cawhyred** [comment]
> As I experienced before, momo can even detect the status of phone's bootloader. If the bootloader is unlocked, momo won't work. Still, you want to use momo, your best bet is going back to stock rom with locked bootloader or use the app on another phone.
I think there is some misunderstanding, I am using momo just to demonstrate that using this module causes some magisk files appear to on device which result in some banking detecting the device is using magisk.
