### ISSUE TITLE
Ksuwebui doesn"t with 0.19 versione 

### ISSUE THREAD

**Issue by cicciocanestro** [j-hc/zygisk-detach#57]
**Are you sure you read the [readme](https://github.com/j-hc/zygisk-detach#usage)?**
Yes

**Android version and skin (MIUI etc... is MIUI still a thing? idk):**
Android 15. Oxygeon 15

**Screenshot of Play Store page of the app you are trying to detach:**
![Screenshot_2024-12-31-14-10-55-11_ae26140005300a1889275a71498bc9ff](https://github.com/user-attachments/assets/e4bfc5b2-197e-4f5a-8fa1-0dbfb27e0877)

**Screenshot of the helper CLI showing detached apps (from Option 2):**
![Screenshot_2024-12-31-14-17-04-85_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/411b7d4f-3fbf-4968-8dfd-0e84b376eb6b)

**Logs taken with `su -c logcat -d -s "zygisk-detach" > /sdcard/log.txt`:**
Nothing

Not providing this information will get your issue closed

**Comment by j-hc** [comment]
zygisk-detach version?

**Comment by j-hc** [comment]
use 1.19.1 then
