### ISSUE TITLE
Can't detach more than 1 app from playstore!!!

### ISSUE THREAD

**Issue by Arafat0010** [j-hc/zygisk-detach#8]
I need to detach two apps from Play Store but I can detach only one apps from Play Store.
Youtube and Youtube music needs to detach from Play Store.
First one is detached but YouTube music can't be detached.
Here is the screenshot from playstore (Auto updated to latest version):
![Screenshot_2023-09-29-23-15-48-760_com android vending](https://github.com/j-hc/zygisk-detach/assets/134326236/f44e1a12-e53b-47c5-922e-5663fc7b5b81)

In the module it’s showing both of them are in detached list. If I open the module and go to Re-attach(2nd option from CLI) It's showing both of them have already detached.
Here is the screenshot:
![Screenshot_2023-09-29-23-19-52-472_com termux](https://github.com/j-hc/zygisk-detach/assets/134326236/db5dcbbe-bbb7-4f64-864d-8b2a6760166c)

So I am confused and don't know how to solve it. It’s annoying to patch Youtube music everytime it’s get an update.
You have wanted the log of zygisk detach, here is the link of [Zygisk-detach log.txt](https://drive.google.com/file/d/17abdF3teWkOoyKKBIAWMGhqByeJJTLIF/view?usp=drivesdk) 

Hope you will give me a solution to this problem.

Note: Sorry for my bad English.

**Comment by j-hc** [comment]
logs show that detach.bin is empty. grab the `/data/adb/modules/zygisk-detach/detach.bin` file using a root file manager and send it here

**Comment by Arafat0010** [comment]
> logs show that detach.bin is empty. grab the `/data/adb/modules/zygisk-detach/detach.bin` file using a root file manager and send it here

Here is [Detach.bin](https://drive.google.com/file/d/186aW_gxOQ7KtWA96BmP18NBlK0YnoEbs/view?usp=drivesdk)

**Comment by j-hc** [comment]
try v1.7
